### ISSUE TITLE
think u meant to install standard and not standardjs

### ISSUE THREAD

**Issue by jimmywarting** [dawidjaniga/codecity#2]
https://github.com/dawidjaniga/codecity/blob/80ac1d768e260b8063e4b9c6c1c28dd8b52f0940/package.json#L19

**Comment by dawidjaniga** [comment]
That's right Jimmy. Thank you for letting me know 👍🏻

**Comment by jimmywarting** [comment]
np, gona have to watch each others back if similar package tries to do something harmful
